# Generated by Django 4.2.4 on 2023-08-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_registration', '0002_staff_email_alter_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(default='not_defined yet', max_length=6),
            preserve_default=False,
        ),
    ]
