# Generated by Django 4.2.4 on 2023-08-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='learners',
        ),
        migrations.DeleteModel(
            name='myInstitution',
        ),
        migrations.DeleteModel(
            name='supportingstaff',
        ),
        migrations.DeleteModel(
            name='teachingstaff',
        ),
    ]
