# Generated by Django 4.2.4 on 2023-08-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LIN', models.CharField(auto_created=True, max_length=11, null=True)),
                ('firstName', models.CharField(max_length=100)),
                ('sirname', models.CharField(max_length=100)),
                ('otherNames', models.CharField(blank=True, max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('isOrphan', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('districtOfBirth', models.CharField(max_length=100)),
                ('is_refugee', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('nationality', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='learners/')),
            ],
        ),
    ]
