# Generated by Django 4.2.4 on 2023-08-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learners',
            name='has_NIN',
        ),
    ]
