# Generated by Django 4.2.4 on 2023-08-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0002_remove_learners_has_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='learners',
            name='LIN',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
