# Generated by Django 4.2.4 on 2023-08-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0002_learners_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learners',
            name='LIN',
            field=models.CharField(auto_created=True, max_length=11, null=True, unique=True),
        ),
    ]
