# Generated by Django 4.2.4 on 2023-08-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0003_learners_lin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learners',
            old_name='surname',
            new_name='sirname',
        ),
    ]
