# Generated by Django 4.2.4 on 2023-08-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0004_rename_surname_learners_sirname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myInstitution',
        ),
        migrations.DeleteModel(
            name='supportingstaff',
        ),
        migrations.DeleteModel(
            name='teachingstaff',
        ),
        migrations.AlterField(
            model_name='learners',
            name='LIN',
            field=models.CharField(auto_created=True, max_length=11, null=True),
        ),
    ]
