from django.db import models
from django.contrib.auth.models import AbstractUser,Group, Permission


# Create your models here.
class School(AbstractUser):
    userEmail = models.EmailField(max_length=100, null=False, blank=False)
    firstName = models.TextField(max_length=50, null=False, blank=False)
    lastname = models.TextField(max_length=50, null=False, blank=False)
    userPassword = models.TextField(max_length=50, null=False, blank=False)
    institutionType = models.TextField(max_length=50, null=False, blank=False)
    schoolName = models.TextField(max_length=50, null=False, blank=False)
    autoGeneratedEmisNumber = models.TextField(max_length=50, null=True)

    groups = models.ManyToManyField(Group, related_name='schools')
    user_permissions = models.ManyToManyField(Permission, related_name='schools')



    def __str__(self):
        return self.userEmail
    
