from django.shortcuts import render
from .models import School
from django.contrib import messages
import random


# Create your views here.
def register(request):
    return render(request, "register.html")

# Generate student lin number
def generate_EMISnumber_number():
    lin_number = "EU"
    for _ in range(5):
        lin_number += str(random.randint(0, 9))
    return lin_number

def register_user_view(request):
    if request.method == "POST":
        user_email = request.POST.get("Useremail")
        user_first_name = request.POST.get("Userfirstname")
        user_last_name = request.POST.get("Userlastname")
        user_password = request.POST.get("Userpassword")
        user_school_name = request.POST.get("Userschoolname")
        user_institution_type = request.POST.get("institutionType")

                # pass nationality initial to the auto generate lin function
        EMISnumber = generate_EMISnumber_number()
        # check_for_NINS = learners.objects.all()
        for everyNin in School.objects.all():
            while EMISnumber == everyNin:
                EMISnumber = generate_EMISnumber_number()

        # Create a new user
        school = School(
            userEmail=user_email,
            firstName=user_first_name,
            lastname=user_last_name,
            userPassword=user_password,
            institutionType=user_institution_type,
            schoolName=user_school_name,
            autoGeneratedEmisNumber=EMISnumber,
        )
        school.save()
        messages.success(request, "School registered  successfully")
        return render(request, "dashboard.html")
    else:
        messages.error(request, "An Error occured while registering the school")
        return render(request, "register.html")
