# Generated by Django 4.2.4 on 2023-08-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=254)),
                ('firstName', models.TextField(max_length=254)),
                ('lastname', models.TextField(max_length=254)),
                ('userPassword', models.TextField(max_length=50)),
                ('institutionType', models.TextField(max_length=50)),
            ],
        ),
    ]
