# Generated by Django 4.2.4 on 2023-08-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_school_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='firstName',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='lastname',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='schoolName',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='userEmail',
            field=models.EmailField(max_length=100),
        ),
    ]
