# Generated by Django 4.2.4 on 2023-08-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_school_firstname_alter_school_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='autoGeneratedEmisNumber',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
