# Generated by Django 4.2.4 on 2023-08-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_school_options_alter_school_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='userEmail',
        ),
        migrations.RemoveField(
            model_name='school',
            name='userPassword',
        ),
        migrations.AlterField(
            model_name='school',
            name='password',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='username',
            field=models.EmailField(max_length=100),
        ),
    ]
