# Generated by Django 4.2.4 on 2023-08-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_school_useremail_remove_school_userpassword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
