# Generated by Django 4.2.4 on 2023-08-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_email',
        ),
    ]
